name: Dev Build

on:
  push:
    branches:
      - develop

jobs:
  publish_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Test
        run: go test -v ./...

      - name: Publish
        uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets._GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "1.19"
          binary_name: "latest-dev"

